<hr><hr>

# Programação com arrays: introdução ao NumPy

In [2]:
#conda install numpy
import numpy as np

# Construindo Array

In [3]:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [4]:
np.array([4,5,6,9])

array([4, 5, 6, 9])

In [5]:
npa = np.array(range(10))
npa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
npa_zeros = np.zeros(10)
npa_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
npa_ones = np.ones(10)
npa_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
npa_zeros = np.zeros(10, dtype=int)
npa_zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
npa_completo = np.full(10,42)
npa_completo

array([42, 42, 42, 42, 42, 42, 42, 42, 42, 42])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#aleatorios
npa = np.random.randint(10, size = (3,4))
npa

array([[4, 7, 0, 6],
       [0, 5, 5, 9],
       [4, 6, 2, 4]])

In [14]:
np.array([[4,7,0,6],[0,5,5,9],[4,6,2,4]])

array([[4, 7, 0, 6],
       [0, 5, 5, 9],
       [4, 6, 2, 4]])

# Propriedades

In [16]:
npa_zeros.ndim

1

In [17]:
npa.ndim

2

In [18]:
npa_zeros.shape

(10,)

In [19]:
npa.shape

(3, 4)

In [20]:
npa_zeros.size

10

In [21]:
npa.size

12

In [22]:
npa_zeros.dtype

dtype('int32')

In [24]:
npa_ones.dtype

dtype('float64')

In [25]:
npa_ones.nbytes

80

In [26]:
npa_zeros.nbytes

40

# Indexando e Acesso

In [30]:
npa = np.arange(10)*10
npa

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [31]:
npa[0]

0

In [32]:
npa[3]

30

In [33]:
npa[-1]

90

In [34]:
npa[-3]

70

In [35]:
mat = np.array([[4,7,0,6],[0,5,5,9],[4,6,2,4]])
mat

array([[4, 7, 0, 6],
       [0, 5, 5, 9],
       [4, 6, 2, 4]])

In [37]:
mat[1,3]

9

### Subarray

In [38]:
npa = np.arange(10)*10
npa

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
npa[:4]

array([ 0, 10, 20, 30])

In [40]:
npa[4:]

array([40, 50, 60, 70, 80, 90])

In [41]:
npa[4:7]

array([40, 50, 60])

In [42]:
npa[::2]

array([ 0, 20, 40, 60, 80])

In [43]:
npa[2:7:2]

array([20, 40, 60])

# Exercicio

1. criar um numpy array de tamanho 20 aleatório (a sua escolha). <br>
2. remover os 5 primeiros e os 5 últimos elementos do array.

In [50]:
np.random.rand(20)

array([0.29795094, 0.84377431, 0.62146549, 0.70971538, 0.82037892,
       0.69350526, 0.82163701, 0.12851234, 0.04550127, 0.82903163,
       0.99419257, 0.09665753, 0.20865867, 0.10806528, 0.74667067,
       0.93146326, 0.14324945, 0.96774579, 0.55153952, 0.78026034])

In [54]:
npa = np.random.randint(1000, size = 20)
npa

array([501, 922, 312, 282, 757, 700, 809, 497, 683, 896, 626, 291, 985,
       744,  47, 775, 532, 992, 665, 956])

In [55]:
npa[5:]

array([700, 809, 497, 683, 896, 626, 291, 985, 744,  47, 775, 532, 992,
       665, 956])

In [56]:
npa[:-5]

array([501, 922, 312, 282, 757, 700, 809, 497, 683, 896, 626, 291, 985,
       744,  47])

In [57]:
npa[5:-5]

array([700, 809, 497, 683, 896, 626, 291, 985, 744,  47])

# Reshape

In [60]:
vet = np.arange(1,65)
vet

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [61]:
xadrez = vet.reshape(8,8)
xadrez

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [64]:
vet1 = np.arange(10)
vet2 = np.random.randint(10,size=5)
print(vet1)
print(vet2)

[0 1 2 3 4 5 6 7 8 9]
[0 5 9 2 0]


In [66]:
np.concatenate([vet1,vet2])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 5, 9, 2, 0])

In [67]:
mat1 = np.array([[2],[6]])
mat1

array([[2],
       [6]])

In [68]:
mat2 = np.array([[12],[5]])
mat2

array([[12],
       [ 5]])

In [69]:
np.vstack([mat1,mat2])

array([[ 2],
       [ 6],
       [12],
       [ 5]])

In [70]:
np.hstack([mat1,mat2])

array([[ 2, 12],
       [ 6,  5]])

# Splitting

In [72]:
npa = np.random.rand(10)
npa

array([0.92478451, 0.95512802, 0.68786047, 0.19153659, 0.55484377,
       0.07505675, 0.53341523, 0.51701018, 0.21209615, 0.94789207])

In [73]:
np.split(npa,[2])

[array([0.92478451, 0.95512802]),
 array([0.68786047, 0.19153659, 0.55484377, 0.07505675, 0.53341523,
        0.51701018, 0.21209615, 0.94789207])]

In [74]:
np.split(npa,[2,7])

[array([0.92478451, 0.95512802]),
 array([0.68786047, 0.19153659, 0.55484377, 0.07505675, 0.53341523]),
 array([0.51701018, 0.21209615, 0.94789207])]

In [78]:
res = np.split(npa,[2,7])
res[2]

array([0.51701018, 0.21209615, 0.94789207])

In [79]:
res1,res2,res3 = np.split(npa,[2,7])

In [80]:
print(res1)

[0.92478451 0.95512802]


In [81]:
print(res2)

[0.68786047 0.19153659 0.55484377 0.07505675 0.53341523]


In [82]:
print(res3)

[0.51701018 0.21209615 0.94789207]


In [83]:
xadrez

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [84]:
np.hsplit(xadrez,[4])

[array([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [17, 18, 19, 20],
        [25, 26, 27, 28],
        [33, 34, 35, 36],
        [41, 42, 43, 44],
        [49, 50, 51, 52],
        [57, 58, 59, 60]]),
 array([[ 5,  6,  7,  8],
        [13, 14, 15, 16],
        [21, 22, 23, 24],
        [29, 30, 31, 32],
        [37, 38, 39, 40],
        [45, 46, 47, 48],
        [53, 54, 55, 56],
        [61, 62, 63, 64]])]

In [85]:
np.vsplit(xadrez,[4])

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32]]),
 array([[33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])]

# Agregações e Operadores

In [87]:
vet = np.random.randint(10, size = 10)
vet

array([2, 8, 7, 3, 1, 0, 0, 8, 6, 7])

In [89]:
#media
soma = 0
for i in vet:
    soma += i
soma/10

4.2

In [90]:
#media
vet.mean()

4.2

In [91]:
vet.sum()

42

In [94]:
np.arange(1,101).sum()

5050

In [95]:
vet.max()

8

In [96]:
vet.min()

0

In [97]:
np.median(vet)

4.5

In [98]:
np.std(vet)

3.1559467676119

In [99]:
np.var(vet)

9.96

In [100]:
np.std(vet)**2

9.959999999999999

# Operações 

In [101]:
vet = np.ones(10)
vet

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [102]:
vet2 = vet*8
vet2

array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

In [107]:
vet2 = vet+8
vet2

array([9., 9., 9., 9., 9., 9., 9., 9., 9., 9.])

In [104]:
vet3 = np.arange(10)
vet3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
vet2+vet3

array([ 8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.])

In [106]:
np.matmul(vet2,vet3)

360.0

In [109]:
vet = [5,8,2,3,4]
vet

[5, 8, 2, 3, 4]

In [130]:
vet.sort(reverse=1)

In [131]:
vet

[8, 5, 4, 3, 2]

In [114]:
avet = np.array([5,8,2,3,4])
avet

array([5, 8, 2, 3, 4])

In [132]:
avet.sort()
avet[::-1]

array(['c', 'b', 'a'], dtype='<U1')

In [128]:
avet = np.array(['c','a','b'])
avet.sort()
avet

array(['a', 'b', 'c'], dtype='<U1')